chain:
    bech32_prefix: oppy
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - pricefeed
        - staking
        - distribution
        - history
node:
    type: remote
    config:
        rpc:
            client_name: oppy
            address: https://rpc.oppy.zone
            max_connections: 20
        grpc:
            address:  http://rpc.oppy.zone:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: false
    genesis_file_path: /home/ubuntu/genesis.json
database:
    name: joltifyHELKP
    host: localhost
    port: 5432
    user: george
    password: YOURPASSWORD
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: JOLT
          units:
            - denom: JOLT
              exponent: 18
            - denom: atom
              exponent: 18
              price_id: JOLT
        - name: Photino
          units:
            - denom: uptn
              exponent: 0
            - denom: ptn
              exponent: 6
distribution:
    rewards_frequency: 100
